[package]
name = "dec-number-sys"
version = "0.0.3"
authors = ["Dariusz Depta <dariusz.depta@engos.software>"]
description = "Rust bindings to decNumber C library"
documentation = "https://docs.rs/dec-number-sys"
repository = "https://github.com/EngosSoftware/decNumber.sys.git"
license = "MIT"
edition = "2021"

links = "decNumber64"

[dependencies]
libc = "0.2.126"